apiVersion: v1
kind: ServiceAccount
metadata:
  name: swagger-mcp-go
  namespace: swagger-mcp-go
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: swagger-mcp-go
  name: swagger-mcp-go-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swagger-mcp-go-rolebinding
  namespace: swagger-mcp-go
subjects:
- kind: ServiceAccount
  name: swagger-mcp-go
  namespace: swagger-mcp-go
roleRef:
  kind: Role
  name: swagger-mcp-go-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: swagger-mcp-go-netpol
  namespace: swagger-mcp-go
spec:
  podSelector:
    matchLabels:
      app: swagger-mcp-go
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80