global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Swagger MCP Go instances
  - job_name: 'swagger-mcp-go'
    static_configs:
      - targets: ['swagger-mcp-go:8080', 'swagger-mcp-go-jsonplaceholder:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Nginx load balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s